function App() {
  return (
    <div className="app-shell">
      <div className="app-backdrop" aria-hidden="true" />
      <header className="topbar">
        <div>
          <p className="eyebrow">SendSecure</p>
          <h1>Secure transfer operations, designed for clarity.</h1>
        </div>
        <div className="topbar-status" aria-label="Workspace status">
          <span className="status-dot" />
          Ready for phased build-out
        </div>
      </header>

      <main className="content-grid">
        <section className="hero card">
          <div className="hero-copy">
            <p className="section-label">Phase 1</p>
            <h2>Build a frontend that can grow into the full SendSecure workflow.</h2>
            <p>
              This shell gives the project a deliberate structure: a transfer composer, an
              operational surface for status, and a secure layout that can be wired to the API
              in the next phase.
            </p>
          </div>
          <div className="hero-points">
            <div>
              <span className="point-value">Encrypted</span>
              <span className="point-label">UI paths reserved for sensitive actions</span>
            </div>
            <div>
              <span className="point-value">Adaptive</span>
              <span className="point-label">Responsive layout for desktop and mobile</span>
            </div>
            <div>
              <span className="point-value">No mocks</span>
              <span className="point-label">Planned for live runtime data only</span>
            </div>
          </div>
        </section>

        <section className="card composer-card">
          <div className="section-header">
            <div>
              <p className="section-label">Transfer composer</p>
              <h3>Prepare a secure delivery request.</h3>
            </div>
            <span className="pill">Frontend scaffold</span>
          </div>

          <form className="composer-form">
            <label>
              <span>Recipient</span>
              <input type="email" placeholder="recipient@company.com" autoComplete="email" />
            </label>
            <label>
              <span>Subject</span>
              <input type="text" placeholder="Transfer title" autoComplete="off" />
            </label>
            <label>
              <span>Expiry</span>
              <input type="text" placeholder="Set by policy" autoComplete="off" />
            </label>
            <label>
              <span>Access code</span>
              <input type="password" placeholder="Generated by policy" autoComplete="new-password" />
            </label>
            <label className="composer-file">
              <span>Payload</span>
              <div className="file-dropzone">
                <strong>Drop files here</strong>
                <span>Uploads will be validated and attached in the next phase.</span>
              </div>
            </label>
            <button type="button" className="primary-action">
              Continue to delivery setup
            </button>
          </form>
        </section>

        <section className="card state-card">
          <div className="section-header">
            <div>
              <p className="section-label">Operational view</p>
              <h3>Current workspace state.</h3>
            </div>
          </div>
          <div className="state-list">
            <article>
              <span className="state-title">Runtime config</span>
              <span className="state-copy">Ready for environment-driven values.</span>
            </article>
            <article>
              <span className="state-title">API connection</span>
              <span className="state-copy">Will connect once the backend contract is added.</span>
            </article>
            <article>
              <span className="state-title">Security model</span>
              <span className="state-copy">Designed to keep secrets out of source control.</span>
            </article>
          </div>
        </section>
      </main>
    </div>
  );
}

export default App;
